---
abstract: 'Declarative data validation for variables and subroutines'
author:
  - 'Damian Conway <DCONWAY@CPAN.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Checks
no_index:
  directory:
    - t
    - inc
requires:
  PPR: '0.001004'
  Test::More: '0'
  Variable::Magic: '0.63'
  perl: '5.022'
version: '0.000001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
