name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.38'
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
    name: Perl ${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -V

      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps --with-develop .

      - name: Run tests
        id: run-tests
        if: ${{ success() }}
        run: |
          prove -lr --jobs $(nproc --all) --state save

      - name: Archive .prove (for 30 days)
        uses: actions/upload-artifact@master
        if: ${{ failure() && steps.run-tests.conclusion == 'failure' }}
        with:
          name: .prove-${{ matrix.perl }}
          path: .prove
